{
 "title": "resource-average",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "resolution",
    "query": "1s, 5s, 10s, 15s, 30s, 1m, 3m, 5m, 10m, 15m, 30m, 1h"
   },
   {
    "name": "controller_namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash,controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$controller_namespace\"},controller_class)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$controller_namespace\", controller_class=~\"$controller_class\"},controller_pod)"
    }
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$controller_namespace\", controller_class=~\"$controller_class\", controller_pod=~\"$controller\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Template",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Requests/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(avg(irate(nginx_ingress_controller_requests[5m:10s])) by (ingress), 0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg CPU Usage/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Memory Usage/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "round(avg(container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) by (namespace), 0.01)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Per Ingress: Average Request/s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(irate(nginx_ingress_controller_requests[$__rate_interval])) by (ingress)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Resoure Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Per Ingress: Average Request/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller_namespace\",ingress=~\"$ingress\"}[$__rate_interval])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}