---
## --- SERVICE MONITOR ---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foo-servicemonitor
  namespace: foo-deployment
  labels:
    app.kubernetes.io/name: foo-deployment
spec:
  selector:
    matchLabels:
      #app: foo-deployment
      app.kubernetes.io/name: foo-deployment
  #endpoints:
  #  #- port: metrics
  #  #- port: http-service
  #  #  path: /metrics
  #  - interval: 5s