## -- SEE REFERENCE: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
controller:

  ## - RESOURCES - ##
  #resources:
  #  requests:
  #    cpu: 100m
  #    memory: 150Mi
  #replicaCount: 2

  ## - AUTOSCALING - ##
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 100
    targetMemoryUtilizationPercentage: ""
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 30
        policies:
        #- type: Pods
        #  value: 1
        #  periodSeconds: 30
        - type: Percent           # The autoscaler will remove 50% of the current replica number in periodSeconds.
          value: 50
          periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
        - type: Pods
          value: 1
          periodSeconds: 15

  ## - METRICS - ##
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: ""      # Default to the deployment namespace"
      scrapeInterval: ""